@startuml
'https://plantuml.com/use-case-diagram

left to right direction

actor 用户 as user

usecase 管理 as manager
usecase 对象访问 as object_visit
usecase 对象管理 as object_manager
usecase 桶操作 as bucket_operation
usecase 数据源操作 as data_source_operation
usecase 登陆 as login

usecase 上传文件 as upload_file
usecase 下载文件 as download_file
usecase 删除文件 as delete_file
usecase 创建直链 as create_link
usecase 删除直链 as delete_link
usecase 导出直链 as export_link

usecase 查看桶 as view_bucket
usecase 添加桶 as add_bucket
usecase 搜索桶 as search_bucket
usecase 删除桶 as delete_bucket
usecase 修改桶 as modify_bucket
usecase 查看数据源 as view_data_source
usecase 查看桶数据 as view_bucket_data

usecase 添加数据源 as add_data_source
usecase 删除数据源 as delete_data_source

user --> login
user -->object_visit
user --> view_bucket

login --> manager

manager --> bucket_operation
manager --> data_source_operation
manager --> object_manager

object_visit --> upload_file
object_visit --> download_file
object_visit --> export_link

bucket_operation --> add_bucket
bucket_operation --> search_bucket
bucket_operation --> delete_bucket
bucket_operation --> modify_bucket

view_bucket --> view_bucket_data
view_bucket --> view_data_source

object_manager --> delete_file
object_manager --> create_link
object_manager --> delete_link

data_source_operation --> add_data_source
data_source_operation --> delete_data_source


@enduml