import QtQuick

QtObject {
    property color rosewater: "#dc8a78"
    property color flagingo: "#dd7878"
    property color pink: "#ea76cb"
    property color mauve: "#8839ef"
    property color red: "#d20f39"
    property color maroon: "#e64553"
    property color peach: "#fe640b"
    property color yellow: "#df8e1d"
    property color green: "#40a02b"
    property color teal: "#179299"
    property color sky: "#04a5e5"
    property color sapphire: "#209fb5"
    property color blue: "#1e66f5"
    property color lavender: "#7287fd"
    property color text: "#4c4f69"
    property color subtext1: "#5c5f77"
    property color subtext0: "#6c6f85"
    property color overlay2: "#7c7f93"
    property color overlay1: "#8c8fa1"
    property color overlay0: "#9ca0b0"
    property color surface2: "#acb0be"
    property color surface1: "#bcc0cc"
    property color surface0: "#ccd0da"
    property color base: "#eff1f5"
    property color mantle: "#e6e9ef"
    property color crust: "#dce0e8"
}
